### ISSUE TITLE
Gardine vs. deleted apps

### ISSUE THREAD

**Issue by slavalamp** [yauhen-l/gardine#4]
1. "Use icons" is disabled.
2. I open a random app.
3. I delete it. It stays in the widget.
4. I switch to it using Gardine.
5. Gardine crashes.
6. I open it again and enable "Use icons".
7. Gardine's widget doesn't show apps anymore, there's only one empty line (as when there are no recent apps).

Disabling and enabling the widget doesn't fix this, but force stop does.

**Comment by yauhen-l** [comment]
Hi @s-goryan ,
Thank you for this bug report. 
1. Definitely deleted apps should not show up in the widget.
2. And even if application cannot be resumed due to any reason Gardine should not crash.
